<?php 
	define('DBhost','localhost');
	define('DBuser','ashram7');
	define('DBpass','ay2111!!');
	define('DBname','ashram7');
	//define('DBhost','ashram7.dothome.co.kr');
	//define('DBuser','ashram7');
	//define('DBpass','ay2111!!');
	//define('DBname','ashram7');
?>